const policyData = [
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLA",
    sufix: "B1",
    type: "Alphard",
    category: "Passenger",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "DLRPickup",
    plantCode: "0-import",
    modelPrintSequence: "16058",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLC",
    sufix: "A1",
    type: "Alphard",
    category: "Passenger",
    domesticExport: "Export",
    assignType: "FirmOrder",
    holdInvoice: "None",
    modelPickupFlag: "TTTPickup",
    plantCode: "0-import",
    modelPrintSequence: "16057",
    automaticYardInFlag: "No",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLD",
    sufix: "c1",
    type: "Alphard",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "DLRPickup",
    plantCode: "",
    plantCode: "0-import",
    modelPrintSequence: "16059",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "G1",
    type: "Alphard",
    category: "Passenger",
    domesticExport: "Domestic",
    assignType: "NonFirmOrder",
    holdInvoice: "Recall",
    modelPickupFlag: "DLRPickup",
    plantCode: "",
    modelPrintSequence: "16274",
    automaticYardInFlag: "Yes",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "B1",
    type: "Velfire",
    category: "Passenger",
    domesticExport: "Domestic",
    assignType: "NonFirmOrder",
    holdInvoice: "None",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16062",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "A1",
    type: "Velfire",
    category: "Passenger",
    domesticExport: "Domestic",
    assignType: "NonFirmOrder",
    holdInvoice: "Recall",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16061",
    automaticYardInFlag: "No",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "G1",
    type: "Alphard",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "None",
    modelPickupFlag: "DLRPickup",
    plantCode: "",
    modelPrintSequence: "16060",
    automaticYardInFlag: "No",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "C1",
    type: "Alphard",
    category: "Commercial",
    domesticExport: "Export",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16055",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "D1",
    type: "Lexus",
    category: "Commercial",
    domesticExport: "Export",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16056",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "03",
    type: "Lexus",
    category: "Passenger",
    domesticExport: "Export",
    assignType: "FirmOrder",
    holdInvoice: "None",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16057",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "02",
    type: "Lexus",
    category: "Passenger",
    domesticExport: "Export",
    assignType: "NonFirmOrder",
    holdInvoice: "Recall",
    modelPickupFlag: "DLRPickup",
    plantCode: "",
    modelPrintSequence: "16052",
    automaticYardInFlag: "Yes",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "01",
    type: "Lexus",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "NonFirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16053",
    automaticYardInFlag: "No",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "BBII55R-PFXLB",
    sufix: "01",
    type: "Lexus",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16054",
    automaticYardInFlag: "Yes",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "BBII55R-PFXLB",
    sufix: "03",
    type: "Lexus",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16051",
    automaticYardInFlag: "No",
    evFlag: "Yes",
  },
];
export const filterPolicyData = (model, category, assignType) => {
  let filtersedList = policyData;
  if (model) {
    filtersedList = filtersedList.filter(
      (item) => item.model.indexOf(model) != -1
    );
  }
  if (category) {
    filtersedList = filtersedList.filter(
      (item) => item.category.indexOf(category) != -1
    );
  }
  if (assignType) {
    filtersedList = filtersedList.filter(
      (item) => item.assignType.indexOf(assignType) != -1
    );
  }
  return filtersedList;
};
