const policyData = [

  {
    assignTypeCode: "1",
    holdInvoiceCode: "",
    evFlagCode: "N",
    evFlag: "No",
    assignType: "FirmOrder",
    categoryCode: "P",
    type: "Alphard",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "Y",
    typeCode: "ALPH",
    domesticExport: "Domestic",
    modelPrintSequence: "16057",
    automaticYardInFlag: "Yes",
    sufix: "A1",
    model: "AAHH45R-PFXLB",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "0",
    category: "Passenger",
    domesticExportCode: "D",
    modelPickupFlagCode: "T"
  },
  {
    assignTypeCode: "2",
    holdInvoiceCode: "",
    evFlagCode: "N",
    evFlag: "No",
    assignType: "NonFirmOrder",
    categoryCode: "C",
    type: "Coaster",
    modelPickupFlag: "DLRPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "Y",
    typeCode: "COAS",
    domesticExport: "Domestic",
    modelPrintSequence: "1981",
    automaticYardInFlag: "Yes",
    sufix: "09",
    model: "BB42R-ZRMSS",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "0",
    category: "Commercial",
    domesticExportCode: "D",
    modelPickupFlagCode: "D"
  },
  {
    assignTypeCode: "1",
    holdInvoiceCode: "",
    evFlagCode: "N",
    evFlag: "No",
    assignType: "FirmOrder",
    categoryCode: "C",
    type: "HiluxRevo_D",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "Y",
    typeCode: "HR4D",
    domesticExport: "Export",
    modelPrintSequence: "12472",
    automaticYardInFlag: "Yes",
    sufix: "R3",
    model: "GUN125L-DTFMHV",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "F",
    category: "Commercial",
    domesticExportCode: "E",
    modelPickupFlagCode: "T"
  },
  {
    assignTypeCode: "1",
    holdInvoiceCode: "",
    evFlagCode: "N",
    evFlag: "No",
    assignType: "FirmOrder",
    categoryCode: "C",
    type: "Hilux4X2",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "Y",
    typeCode: "HLU2",
    domesticExport: "Domestic",
    modelPrintSequence: "108",
    automaticYardInFlag: "Yes",
    sufix: "11",
    model: "KDN151R-CRMSYT",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "B",
    category: "Commercial",
    domesticExportCode: "D",
    modelPickupFlagCode: "T"
  },
  {
    assignTypeCode: "1",
    holdInvoiceCode: "",
    evFlagCode: "N",
    evFlag: "No",
    assignType: "FirmOrder",
    categoryCode: "P",
    type: "Soluna",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "Y",
    typeCode: "SONA",
    domesticExport: "Domestic",
    modelPrintSequence: "652",
    automaticYardInFlag: "Yes",
    sufix: "G1",
    model: "AL50R-AEPNK-A",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "C",
    category: "Passenger",
    domesticExportCode: "D",
    modelPickupFlagCode: "T"
  },
  {
    assignTypeCode: "1",
    holdInvoiceCode: "",
    evFlagCode: "N",
    evFlag: "No",
    assignType: "FirmOrder",
    categoryCode: "C",
    type: "Commuter",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "Y",
    typeCode: "COMM",
    domesticExport: "Export",
    modelPrintSequence: "11789",
    automaticYardInFlag: "Yes",
    sufix: "HE",
    model: "KDH223L-LEMDYU",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "D",
    category: "Commercial",
    domesticExportCode: "E",
    modelPickupFlagCode: "T"
  },
  {
    assignTypeCode: "1",
    holdInvoiceCode: "1",
    evFlagCode: "N",
    evFlag: "No",
    assignType: "FirmOrder",
    categoryCode: "P",
    type: "Camry",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "New Model",
    automaticYardInFlagCode: "Y",
    typeCode: "CARY",
    domesticExport: "Domestic",
    modelPrintSequence: "627",
    automaticYardInFlag: "Yes",
    sufix: "01",
    model: "SXV20R-JEPEKT",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "B",
    category: "Passenger",
    domesticExportCode: "D",
    modelPickupFlagCode: "T"
  },
  {
    assignTypeCode: "1",
    holdInvoiceCode: "",
    evFlagCode: "N",
    evFlag: "No",
    assignType: "FirmOrder",
    categoryCode: "P",
    type: "Corolla",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "",
    typeCode: "COLA",
    domesticExport: "Domestic",
    modelPrintSequence: "1110",
    automaticYardInFlag: "No",
    sufix: "10",
    model: "ZZE121R-GEPNKTA",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "C",
    category: "Passenger",
    domesticExportCode: "D",
    modelPickupFlagCode: "T"
  },
  {
    assignTypeCode: "1",
    holdInvoiceCode: "",
    evFlagCode: "N",
    evFlag: "No",
    assignType: "FirmOrder",
    categoryCode: "P",
    type: "Corolla",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "",
    typeCode: "COLA",
    domesticExport: "Domestic",
    modelPrintSequence: "1111",
    automaticYardInFlag: "No",
    sufix: "10",
    model: "ZZE121R-GEPDKT",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "C",
    category: "Passenger",
    domesticExportCode: "D",
    modelPickupFlagCode: "T"
  },
  {
    assignTypeCode: "1",
    holdInvoiceCode: "",
    evFlagCode: "Y",
    evFlag: "Yes",
    assignType: "FirmOrder",
    categoryCode: "P",
    type: "bZ4X",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "Y",
    typeCode: "C-HI",
    domesticExport: "Domestic",
    modelPrintSequence: "15838",
    automaticYardInFlag: "Yes",
    sufix: "11",
    model: "YEAM15R-MWDHSW",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "0",
    category: "Passenger",
    domesticExportCode: "D",
    modelPickupFlagCode: "T"
  },
  {
    assignTypeCode: "1",
    holdInvoiceCode: "",
    evFlagCode: "Y",
    evFlag: "Yes",
    assignType: "FirmOrder",
    categoryCode: "P",
    type: "bZ4X",
    modelPickupFlag: "TTTPickup",
    holdInvoice: "None",
    automaticYardInFlagCode: "Y",
    typeCode: "C-HI",
    domesticExport: "Domestic",
    modelPrintSequence: "15839",
    automaticYardInFlag: "Yes",
    sufix: "12",
    model: "YEAM15R-MWDHSW",
    id: "uuid-" + Math.random() * 10000000,
    plantCode: "0",
    category: "Passenger",
    domesticExportCode: "D",
    modelPickupFlagCode: "T"
  },

  /*new ends */



  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLA",
    sufix: "B1",
    type: "Alphard",
    category: "Passenger",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "DLRPickup",
    plantCode: "0-import",
    modelPrintSequence: "16058",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLC",
    sufix: "A1",
    type: "Alphard",
    category: "Passenger",
    domesticExport: "Export",
    assignType: "FirmOrder",
    holdInvoice: "None",
    modelPickupFlag: "TTTPickup",
    plantCode: "0-import",
    modelPrintSequence: "16057",
    automaticYardInFlag: "No",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLD",
    sufix: "c1",
    type: "Alphard",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "DLRPickup",
    plantCode: "",
    plantCode: "0-import",
    modelPrintSequence: "16059",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "G1",
    type: "Alphard",
    category: "Passenger",
    domesticExport: "Domestic",
    assignType: "NonFirmOrder",
    holdInvoice: "Recall",
    modelPickupFlag: "DLRPickup",
    plantCode: "",
    modelPrintSequence: "16274",
    automaticYardInFlag: "Yes",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "B1",
    type: "Velfire",
    category: "Passenger",
    domesticExport: "Domestic",
    assignType: "NonFirmOrder",
    holdInvoice: "None",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16062",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "A1",
    type: "Velfire",
    category: "Passenger",
    domesticExport: "Domestic",
    assignType: "NonFirmOrder",
    holdInvoice: "Recall",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16061",
    automaticYardInFlag: "No",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "G1",
    type: "Alphard",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "None",
    modelPickupFlag: "DLRPickup",
    plantCode: "",
    modelPrintSequence: "16060",
    automaticYardInFlag: "No",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "C1",
    type: "Alphard",
    category: "Commercial",
    domesticExport: "Export",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16055",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "D1",
    type: "Lexus",
    category: "Commercial",
    domesticExport: "Export",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16056",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "03",
    type: "Lexus",
    category: "Passenger",
    domesticExport: "Export",
    assignType: "FirmOrder",
    holdInvoice: "None",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16057",
    automaticYardInFlag: "Yes",
    evFlag: "No",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "02",
    type: "Lexus",
    category: "Passenger",
    domesticExport: "Export",
    assignType: "NonFirmOrder",
    holdInvoice: "Recall",
    modelPickupFlag: "DLRPickup",
    plantCode: "",
    modelPrintSequence: "16052",
    automaticYardInFlag: "Yes",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "AAHH45R-PFXLB",
    sufix: "01",
    type: "Lexus",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "NonFirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16053",
    automaticYardInFlag: "No",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "BBII55R-PFXLB",
    sufix: "01",
    type: "Lexus",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16054",
    automaticYardInFlag: "Yes",
    evFlag: "Yes",
  },
  {
    id: "uuid-" + Math.random() * 10000000,
    model: "BBII55R-PFXLB",
    sufix: "03",
    type: "Lexus",
    category: "Commercial",
    domesticExport: "Domestic",
    assignType: "FirmOrder",
    holdInvoice: "NewModel",
    modelPickupFlag: "TTTPickup",
    plantCode: "",
    modelPrintSequence: "16051",
    automaticYardInFlag: "No",
    evFlag: "Yes",
  },
];
export const filterPolicyData = (model, category, assignType) => {
  let filtersedList = policyData;
  if (model) {
    filtersedList = filtersedList.filter(
      (item) => item.model.indexOf(model) != -1
    );
  }
  if (category) {
    filtersedList = filtersedList.filter(
      (item) => item.category.indexOf(category) != -1
    );
  }
  if (assignType) {
    filtersedList = filtersedList.filter(
      (item) => item.assignType.indexOf(assignType) != -1
    );
  }
  return filtersedList;
};
