const policyData = [
  {
    name: "Tod Miles",
    email: "tod.miles@gmail.com",
    policyNumber: "2023001",
    premiumAmount: 1987.23,
    policyType: "Fire",
    deductible: "Flat",
    effectiveDate: "28/07/2023",
    expirationDate: "27/07/2033",
    term: "term",
    coverages: "coverages",
  },
  {
    name: "Jess Smith",
    email: "jess.smith@gmail.com",
    policyNumber: "2023002",
    premiumAmount: 2000.99,
    policyType: "Burglary",
    deductible: "Percentage",
    effectiveDate: "28/07/2023",
    expirationDate: "27/07/2033",
    term: "term",
    coverages: "coverages",
  },
  {
    name: "Jess Smith",
    email: "jess.smith@gmail.com",
    policyNumber: "2023003",
    premiumAmount: 2000.99,
    policyType: "All Risks",
    deductible: "Waiting Period",
    effectiveDate: "28/07/2023",
    expirationDate: "27/07/2033",
    term: "term",
    coverages: "coverages",
  },
  {
    name: "Olivia Beiry",
    email: "olivia.beiry@gmail.com",
    policyNumber: "2022001",
    premiumAmount: 65785.99,
    policyType: "Earthquake",
    deductible: "Flat",
    effectiveDate: "16/11/2022",
    expirationDate: "17/11/2032",
    term: "term",
    coverages: "coverages",
  },
  {
    name: "John Smith",
    email: "john.smith@gmail.com",
    policyNumber: "2022002",
    premiumAmount: 4567.99,
    policyType: "Flood",
    deductible: "Waiting Period",
    effectiveDate: "26/03/2023",
    expirationDate: "27/03/2033",
    term: "term",
    coverages: "coverages",
  },
  {
    name: "Diana Markus",
    email: "diana.markus@gmail.com",
    policyNumber: "2022003",
    premiumAmount: 2000.99,
    policyType: "All Risks",
    deductible: "Percentage",
    effectiveDate: "28/07/2023",
    expirationDate: "27/07/2033",
    term: "term",
    coverages: "coverages",
  },
  {
    name: "Mathew Graham",
    email: "mathew.graham@gmail.com",
    policyNumber: "2022004",
    premiumAmount: 1987.23,
    policyType: "Flood",
    deductible: "Percentage",
    effectiveDate: "28/07/2023",
    expirationDate: "27/07/2033",
    term: "term",
    coverages: "coverages",
  },
  {
    name: "Emma Smith",
    email: "emma.smith@gmail.com",
    policyNumber: "2022005",
    premiumAmount: 1987.23,
    policyType: "All Risks",
    deductible: "Waiting Period",
    effectiveDate: "28/07/2023",
    expirationDate: "27/07/2033",
    term: "term",
    coverages: "coverages",
  },
  {
    name: "Craig Miles",
    email: "craig.miles@gmail.com",
    policyNumber: "2022006",
    premiumAmount: 1987.23,
    policyType: "Fire",
    deductible: "Percentage",
    effectiveDate: "28/07/2023",
    expirationDate: "27/07/2033",
    term: "term",
    coverages: "coverages",
  },
  {
    name: "Tod Miles",
    email: "tod.miles@gmail.com",
    policyNumber: "2022007",
    premiumAmount: 1987.23,
    policyType: "All Risks",
    deductible: "Waiting Period",
    effectiveDate: "20/07/2022",
    expirationDate: "21/07/2032",
    term: "term",
    coverages: "coverages",
  },
];
export const filterPolicyData = (policyNumber, address) => {
  return policyData.filter(
    (item) => item.policyNumber.indexOf(policyNumber) != -1
  );
};
